name: Build and Publish Container
on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the container image to the registry'
        required: false
        default: false
        type: boolean
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: metaschema-framework/oscal-cli
  # Docs: github.com/docker/metadata-action/?tab=readme-ov-file#typesha
  DOCKER_METADATA_PR_HEAD_SHA: true
  # https://github.com/docker/metadata-action?tab=readme-ov-file#annotations
  DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
jobs:
  build-container:
    name: Build Image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: recursive
        filter: tree:0
    - name: Download build zip
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3
      with:
        name: build_zip
        path: ./target
    - name: Container image QEMU setup for cross-arch builds
      id: image_setup_qemu
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130
    - name: Container image buildx setup for cross-arch builds
      id: image_setup_buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd
      with:
        platforms: linux/amd64,linux/arm64/v8
    - name: Container image login
      id: image_login
      uses: docker/login-action@3227f5311cb93ffd14d13e65d8cc400d30f4dd8a
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Container image metadata and tag generation
      id: image_metadata
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
      with:
        images:
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,prefix=,suffix=,format=long
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
        flavor: |
          latest=auto
        annotations: |
          maintainers="Metaschema Community Admin <admin@metaschema.dev>"
          org.opencontainers.image.authors="Metaschema Community Admin <admin@metaschema.dev>"
          org.opencontainers.image.documentation="https://metaschema.dev"
          org.opencontainers.image.source="https://github.com/metaschema-framework/oscal-cli"
          org.opencontainers.image.vendor="Metaschema Community"
          org.opencontainers.image.title="oscal-cli-extended"
          org.opencontainers.image.description="Metaschema-powered CLI tool for processing OSCAL"
          org.opencontainers.image.licenses="CC0-1.0"
    - if: inputs.push
      name: Container image registry push
      id: image_registry_push
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
      with:
        context: .
        file: ./Dockerfile.ci
        push: true
        tags: ${{ steps.image_metadata.outputs.tags }}
        labels: ${{ steps.image_metadata.outputs.labels }}
        platforms: linux/amd64,linux/arm64/v8
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - if: inputs.push
      name: Container image push attestations
      uses: actions/attest-build-provenance@96278af6caaf10aea03fd8d33a09a777ca52d62f
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.image_registry_push.outputs.digest }}
        push-to-registry: true
